export const ROUTES = {
  HOME: '/',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  ABOUT_US: '/about-us',
  CONTACT_US: '/contact-us',
  QUESTIONS: '/questions',
  CABINET_PERSONAL_INFO: '/cabinet/personal-info',
  CABINET_KYC: '/cabinet/kyc',
  CABINET_SECURITY: '/cabinet/security',
  CABINET_OPEN_ORDERS: '/cabinet/open-orders',
  CABINET_HISTORY: '/cabinet/history',
  CABINET_NOTIFICATIONS: '/cabinet/notifications',
  CABINET_SUPPORT: '/cabinet/support',
  CABINET_DEACTIVATION: '/cabinet/deactivation',
  RECOVERY_PASSWORD: '/recovery-password',
  WALLET: '/cabinet/wallet',
  MARKET: '/market',
  WITHDRAW_CRYPTO: '/withdraw-crypto',
  WITHDRAW_FIAT: '/withdraw-fiat',
  DEPOSIT_CRYPTO: '/deposit-crypto',
  DEPOSIT_FIAT: '/deposit-fiat',
  VERIFICATION: '/verification'
}
