export type TIconProps = {
  id?:
    | 'envelope-open'
    | 'google'
    | 'logo'
    | 'spinner-gap'
    | 'x'
    | 'user-circle'
    | 'circle-wavy-check'
    | 'fingerprint'
    | 'security'
    | 'user-plus'
    | 'card-holder'
    | 'money'
    | 'youtube'
    | 'twitter'
    | 'instagram'
    | 'linkedin'
    | 'facebook'
    | 'eyeSlash'
    | 'eye'
    | 'phone-disconnect'
    | 'warning-circle'
    | 'payment-1'
    | 'user'
    | 'shield-checkered'
    | 'receipt'
    | 'list-dashes'
    | 'user-focus'
    | 'user-circle-minus'
    | 'notifications'
    | 'support'
    | 'lock-key'
    | 'chevron-left'
    | 'chevron-right'
    | 'trash-full'
    | 'envelope'
    | 'map-pin'
    | 'cancel-file'
    | 'file'
    | 'folder'
    | 'info-circle'
    | 'check-circle'
    | 'x-circle'
    | 'user-profile'
    | 'copy'
    | 'bitcoin'
    | 'euro'
    | 'star'
    | 'caret-down'
  size?: 'small' | 'medium' | 'big' | 'mid-big' | 'extra-big'
  colorStroke?: 'none' | 'white' | 'blue' | 'malibu' | 'red' | 'alert' | 'green'
  fill?: 'none' | 'white' | 'blue' | 'malibu' | 'red' | 'alert' | 'green'
  spin?: boolean
}
